[project]
name = "cs224w-final-proj"
version = "0.1.0"
description = "CS224W Final Project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.7",
    "networkx>=3.6",
    "scipy>=1.16.3",
    "torch>=2.9.1",
    "torch-geometric>=2.7.0",
]
