train_ratio: 0.7
val_ratio: 0.15
shuffle: True
seed: 42
design_dir: "./designs"
target_metrics: ["critical_path"] # ["critical_path", "core_area", "power"]
batch_size: 8
hidden_dim: 32
dropout: 0.2
num_layers: 3
bidirectional: False
device: "cpu"
learning_rate: 0.001
num_epochs: 100
save_dir: "./checkpoints"
