train_ratio: 0.7
val_ratio: 0.15
shuffle: True
seed: 42
design_dir: "./designs"
target_metrics: ["critical_path"] # ["critical_path", "core_area", "power"]
batch_size: 32
hidden_dim: 32
dropout: 0.2
num_layers: 2
bidirectional: False
device: "cpu"
learning_rate: 0.001
num_epochs: 100
save_dir: "./checkpoints/critical_path/topo_more_layers"
weight_decay: 0.00001  # 1e-5
lr_scheduler_patience: 10
lr_scheduler_factor: 0.8
lr_scheduler_mode: "min"
model_name: "topo"
